/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.thedrakonir.drakotil;

import com.github.thedrakonir.drakotil.logging.Logger;
import com.github.thedrakonir.drakotil.logging.LoggerFactory;
import com.github.thedrakonir.drakotil.serialization.Stringifier;

import org.junit.Assert;
import org.junit.Test;

public class LibraryTest {

    @Test public void testStringifier() {
        Logger consoleLogger = LoggerFactory.getConsoleLogger();

        Assert.assertEquals("2", Stringifier.stringify(2));
        Assert.assertEquals("2.0", Stringifier.stringify(2.0F));
        System.out.println(Stringifier.stringify(2));
        System.out.println(Stringifier.stringify(2.0F));
        System.out.println(Stringifier.stringify(consoleLogger));
    }
}
